version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fluukpe_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/fluukpe_db
      - OPENAI_API_KEY=
      - REPLICATE_API_KEY=
      - SECRET_KEY=changeme_supersecret
    depends_on:
      - db
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    command: ["npm","run","dev"]
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db-data:
